### ISSUE TITLE
Dimensiones de humanoides

### ISSUE THREAD

**Issue by JavierIH** [open-robosports/normativa-humanoide#1]
Necesito un poco de feedback con las dimensiones de los robots. Sobre todo @robotaleh o @20leunam, podéis echarle un vistazo y ver si vuestro humanoide estaría dentro de la normativa? :grin:

Tengo que revisar tranquilamente las normativas de otras competiciones para ver si podemos compatibilizarlas bien.

**Comment by robotaleh** [comment]
Estoy comparando con el diseño porque no tengo aqui el bicho, pero la medida de anchura no entra ni de blas xD
Solo midiendo de bola a bola (hombros) ya son 27cm. Contando con los bloques de la mano son ~40cm (No puedo medir bien esto porque no estoy seguro de hasta donde permiten doblar los servos)

La longitud del brazo, midiendo desde el centro del robot me sale en 40cm justos

De pierna, midiendo desde el suelo hasta el último eje de la pierna (sin contar el de la ingle que abre lateralmente las piernas) son 28cm. Si hubiese que contar también el eje de la ingle, serían unos 32cm

El pie es justo el 50% de 28 x 30% de 28, al límite pero entra xD

Resumiendo, el problema son los brazos, que son enormes xD

**Comment by JavierIH** [comment]
Pierna y pies perfectos, es lo que dice la Robo-One ([normativa](http://www.robo-one.com/upload/roboones/28_b06c53667d629b16c393238eebf8ad1aoriginal_en.pdf)) así que poco se puede añadir :grin:

Sobre el ancho y los brazos, estoy revisando la normativa y dice que la separación desde el centro del robot hasta el borde del brazo no debe superar un 120% de la medida de las patas. En vuestro caso serian 33.6 cm. Creo que de momento lo que podemos hacer es dejar de lado el tema de proporciones y poner una longitud máxima de pierna de 34cm y una logitud de brazo (desde la cabeza) de 40cm. Así vuestro robot entraría y uno de la Robo-One también.

Luego con el tiempo podemos ir acercándonos poco a poco a la Robo-One ¿Os parece bien?

**Comment by robotaleh** [comment]
Por nuestra parte estaría perfecto. Aun no lo he comentado con Manu pero supongo que no tendrá objeción xD

De todas formas, ahora todos andamos un poco liados y esas cosas, pero en cuanto podamos le haremos un rediseño para adaptarnos a eses 33 que entiendo que sería lo adecuado.
